spring:
  profiles:
    active: dev

--- # 端口
server:
  port: 8080

--- # 豆包AI
doubao:
  enabled: true
  base-url: https://www.doubao.com
  timeout: 180
  session-ttl: 3600
  # API令牌 Bearer Token
  api-key: sk-sHf2Sf0ZFMMcmsC5SalYdEHul9R5xqhgW7SbDn4ij5jski4g
  # 参数配置
  accounts:
    # cookie
    - cookie: ""
      device-id: ""
      fp: ""
      tea-uuid: ""
      web-id: ""
      ms-token: ""